/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Engage API
 * You can find out more about the Umbraco Engage API in [the documentation](https://docs.umbraco.com/umbraco-engage/developers/headless/using-the-marketing-api).
 * OpenAPI spec version: v1
 */
import type {
  AssetsResponseModel,
  NotFoundResult,
  UnauthorizedResult
} from '.././model';

import { customFetch } from '../../custom-fetch';

export type getUmbracoEngageApiV1SegmentationAssetsItemPathResponse200 = {
  data: AssetsResponseModel
  status: 200
}

export type getUmbracoEngageApiV1SegmentationAssetsItemPathResponse401 = {
  data: UnauthorizedResult
  status: 401
}

export type getUmbracoEngageApiV1SegmentationAssetsItemPathResponse404 = {
  data: NotFoundResult
  status: 404
}
    
export type getUmbracoEngageApiV1SegmentationAssetsItemPathResponseComposite = getUmbracoEngageApiV1SegmentationAssetsItemPathResponse200 | getUmbracoEngageApiV1SegmentationAssetsItemPathResponse401 | getUmbracoEngageApiV1SegmentationAssetsItemPathResponse404;
    
export type getUmbracoEngageApiV1SegmentationAssetsItemPathResponse = getUmbracoEngageApiV1SegmentationAssetsItemPathResponseComposite & {
  headers: Headers;
}

export const getGetUmbracoEngageApiV1SegmentationAssetsItemPathUrl = (path: string,) => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/segmentation/assets/item/${path}`
}

export const getUmbracoEngageApiV1SegmentationAssetsItemPath = async (path: string, options?: RequestInit): Promise<getUmbracoEngageApiV1SegmentationAssetsItemPathResponse> => {
  
  return customFetch<getUmbracoEngageApiV1SegmentationAssetsItemPathResponse>(getGetUmbracoEngageApiV1SegmentationAssetsItemPathUrl(path),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getUmbracoEngageApiV1SegmentationAssetsItemIdResponse200 = {
  data: AssetsResponseModel
  status: 200
}

export type getUmbracoEngageApiV1SegmentationAssetsItemIdResponse401 = {
  data: UnauthorizedResult
  status: 401
}

export type getUmbracoEngageApiV1SegmentationAssetsItemIdResponse404 = {
  data: NotFoundResult
  status: 404
}
    
export type getUmbracoEngageApiV1SegmentationAssetsItemIdResponseComposite = getUmbracoEngageApiV1SegmentationAssetsItemIdResponse200 | getUmbracoEngageApiV1SegmentationAssetsItemIdResponse401 | getUmbracoEngageApiV1SegmentationAssetsItemIdResponse404;
    
export type getUmbracoEngageApiV1SegmentationAssetsItemIdResponse = getUmbracoEngageApiV1SegmentationAssetsItemIdResponseComposite & {
  headers: Headers;
}

export const getGetUmbracoEngageApiV1SegmentationAssetsItemIdUrl = (id: string,) => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/segmentation/assets/item/${id}`
}

export const getUmbracoEngageApiV1SegmentationAssetsItemId = async (id: string, options?: RequestInit): Promise<getUmbracoEngageApiV1SegmentationAssetsItemIdResponse> => {
  
  return customFetch<getUmbracoEngageApiV1SegmentationAssetsItemIdResponse>(getGetUmbracoEngageApiV1SegmentationAssetsItemIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


