/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type {
  GetContent20400,
  GetContent20404,
  GetContent20Params,
  GetContent400,
  GetContent404,
  GetContentItem401,
  GetContentItem403,
  GetContentItemById20401,
  GetContentItemById20403,
  GetContentItemById20404,
  GetContentItemById20Params,
  GetContentItemById401,
  GetContentItemById403,
  GetContentItemById404,
  GetContentItemByIdParams,
  GetContentItemByPath20401,
  GetContentItemByPath20403,
  GetContentItemByPath20404,
  GetContentItemByPath20Params,
  GetContentItemByPath401,
  GetContentItemByPath403,
  GetContentItemByPath404,
  GetContentItemByPathParams,
  GetContentItemParams,
  GetContentItems20401,
  GetContentItems20403,
  GetContentItems20Params,
  GetContentParams,
  IApiContentResponseModel,
  PagedIApiContentResponseModel
} from '.././model';

import { customFetch } from '../../custom-fetch';

/**
 * @deprecated
 */
export type getContentResponse200 = {
  data: PagedIApiContentResponseModel
  status: 200
}

export type getContentResponse400 = {
  data: GetContent400
  status: 400
}

export type getContentResponse404 = {
  data: GetContent404
  status: 404
}
    
export type getContentResponseComposite = getContentResponse200 | getContentResponse400 | getContentResponse404;
    
export type getContentResponse = getContentResponseComposite & {
  headers: Headers;
}

export const getGetContentUrl = (params?: GetContentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v1/content?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v1/content`
}

export const getContent = async (params?: GetContentParams, options?: RequestInit): Promise<getContentResponse> => {
  
  return customFetch<getContentResponse>(getGetContentUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getContent20Response200 = {
  data: PagedIApiContentResponseModel
  status: 200
}

export type getContent20Response400 = {
  data: GetContent20400
  status: 400
}

export type getContent20Response404 = {
  data: GetContent20404
  status: 404
}
    
export type getContent20ResponseComposite = getContent20Response200 | getContent20Response400 | getContent20Response404;
    
export type getContent20Response = getContent20ResponseComposite & {
  headers: Headers;
}

export const getGetContent20Url = (params?: GetContent20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v2/content?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v2/content`
}

export const getContent20 = async (params?: GetContent20Params, options?: RequestInit): Promise<getContent20Response> => {
  
  return customFetch<getContent20Response>(getGetContent20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @deprecated
 */
export type getContentItemResponse200 = {
  data: IApiContentResponseModel[]
  status: 200
}

export type getContentItemResponse401 = {
  data: GetContentItem401
  status: 401
}

export type getContentItemResponse403 = {
  data: GetContentItem403
  status: 403
}
    
export type getContentItemResponseComposite = getContentItemResponse200 | getContentItemResponse401 | getContentItemResponse403;
    
export type getContentItemResponse = getContentItemResponseComposite & {
  headers: Headers;
}

export const getGetContentItemUrl = (params?: GetContentItemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v1/content/item?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v1/content/item`
}

export const getContentItem = async (params?: GetContentItemParams, options?: RequestInit): Promise<getContentItemResponse> => {
  
  return customFetch<getContentItemResponse>(getGetContentItemUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @deprecated
 */
export type getContentItemByPathResponse200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemByPathResponse401 = {
  data: GetContentItemByPath401
  status: 401
}

export type getContentItemByPathResponse403 = {
  data: GetContentItemByPath403
  status: 403
}

export type getContentItemByPathResponse404 = {
  data: GetContentItemByPath404
  status: 404
}
    
export type getContentItemByPathResponseComposite = getContentItemByPathResponse200 | getContentItemByPathResponse401 | getContentItemByPathResponse403 | getContentItemByPathResponse404;
    
export type getContentItemByPathResponse = getContentItemByPathResponseComposite & {
  headers: Headers;
}

export const getGetContentItemByPathUrl = (path: string,
    params?: GetContentItemByPathParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v1/content/item/${path}?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v1/content/item/${path}`
}

export const getContentItemByPath = async (path: string,
    params?: GetContentItemByPathParams, options?: RequestInit): Promise<getContentItemByPathResponse> => {
  
  return customFetch<getContentItemByPathResponse>(getGetContentItemByPathUrl(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getContentItemByPath20Response200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemByPath20Response401 = {
  data: GetContentItemByPath20401
  status: 401
}

export type getContentItemByPath20Response403 = {
  data: GetContentItemByPath20403
  status: 403
}

export type getContentItemByPath20Response404 = {
  data: GetContentItemByPath20404
  status: 404
}
    
export type getContentItemByPath20ResponseComposite = getContentItemByPath20Response200 | getContentItemByPath20Response401 | getContentItemByPath20Response403 | getContentItemByPath20Response404;
    
export type getContentItemByPath20Response = getContentItemByPath20ResponseComposite & {
  headers: Headers;
}

export const getGetContentItemByPath20Url = (path: string,
    params?: GetContentItemByPath20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v2/content/item/${path}?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v2/content/item/${path}`
}

export const getContentItemByPath20 = async (path: string,
    params?: GetContentItemByPath20Params, options?: RequestInit): Promise<getContentItemByPath20Response> => {
  
  return customFetch<getContentItemByPath20Response>(getGetContentItemByPath20Url(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @deprecated
 */
export type getContentItemByIdResponse200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemByIdResponse401 = {
  data: GetContentItemById401
  status: 401
}

export type getContentItemByIdResponse403 = {
  data: GetContentItemById403
  status: 403
}

export type getContentItemByIdResponse404 = {
  data: GetContentItemById404
  status: 404
}
    
export type getContentItemByIdResponseComposite = getContentItemByIdResponse200 | getContentItemByIdResponse401 | getContentItemByIdResponse403 | getContentItemByIdResponse404;
    
export type getContentItemByIdResponse = getContentItemByIdResponseComposite & {
  headers: Headers;
}

export const getGetContentItemByIdUrl = (id: string,
    params?: GetContentItemByIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v1/content/item/${id}?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v1/content/item/${id}`
}

export const getContentItemById = async (id: string,
    params?: GetContentItemByIdParams, options?: RequestInit): Promise<getContentItemByIdResponse> => {
  
  return customFetch<getContentItemByIdResponse>(getGetContentItemByIdUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getContentItemById20Response200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemById20Response401 = {
  data: GetContentItemById20401
  status: 401
}

export type getContentItemById20Response403 = {
  data: GetContentItemById20403
  status: 403
}

export type getContentItemById20Response404 = {
  data: GetContentItemById20404
  status: 404
}
    
export type getContentItemById20ResponseComposite = getContentItemById20Response200 | getContentItemById20Response401 | getContentItemById20Response403 | getContentItemById20Response404;
    
export type getContentItemById20Response = getContentItemById20ResponseComposite & {
  headers: Headers;
}

export const getGetContentItemById20Url = (id: string,
    params?: GetContentItemById20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v2/content/item/${id}?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v2/content/item/${id}`
}

export const getContentItemById20 = async (id: string,
    params?: GetContentItemById20Params, options?: RequestInit): Promise<getContentItemById20Response> => {
  
  return customFetch<getContentItemById20Response>(getGetContentItemById20Url(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getContentItems20Response200 = {
  data: IApiContentResponseModel[]
  status: 200
}

export type getContentItems20Response401 = {
  data: GetContentItems20401
  status: 401
}

export type getContentItems20Response403 = {
  data: GetContentItems20403
  status: 403
}
    
export type getContentItems20ResponseComposite = getContentItems20Response200 | getContentItems20Response401 | getContentItems20Response403;
    
export type getContentItems20Response = getContentItems20ResponseComposite & {
  headers: Headers;
}

export const getGetContentItems20Url = (params?: GetContentItems20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/umbraco/delivery/api/v2/content/items?${stringifiedParams}` : `http://localhost:23142/umbraco/delivery/api/v2/content/items`
}

export const getContentItems20 = async (params?: GetContentItems20Params, options?: RequestInit): Promise<getContentItems20Response> => {
  
  return customFetch<getContentItems20Response>(getGetContentItems20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


