/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */

export type GetApiV1SearchGetSearchResultsParams = {
searchQuery?: string;
};
