/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type { SearchResultsItemModel } from './searchResultsItemModel';

export interface SearchResultsModel {
  /** @nullable */
  count?: number | null;
  items?: SearchResultsItemModel[];
}
