/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */

export interface SearchResultsItemModel {
  /** @nullable */
  contentName?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  subtitle?: string | null;
  /** @nullable */
  articleDate?: string | null;
  author?: string;
}
