/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type {
  TranslationModel
} from '.././model';

import { customFetch } from '../../custom-fetch';

export type getApiV1DictionaryGetdictionarytranslationsResponse200 = {
  data: TranslationModel[]
  status: 200
}

export type getApiV1DictionaryGetdictionarytranslationsResponse500 = {
  data: void
  status: 500
}
    
export type getApiV1DictionaryGetdictionarytranslationsResponseComposite = getApiV1DictionaryGetdictionarytranslationsResponse200 | getApiV1DictionaryGetdictionarytranslationsResponse500;
    
export type getApiV1DictionaryGetdictionarytranslationsResponse = getApiV1DictionaryGetdictionarytranslationsResponseComposite & {
  headers: Headers;
}

export const getGetApiV1DictionaryGetdictionarytranslationsUrl = () => {


  

  return `http://localhost:23142/api/v1/dictionary/getdictionarytranslations`
}

export const getApiV1DictionaryGetdictionarytranslations = async ( options?: RequestInit): Promise<getApiV1DictionaryGetdictionarytranslationsResponse> => {
  
  return customFetch<getApiV1DictionaryGetdictionarytranslationsResponse>(getGetApiV1DictionaryGetdictionarytranslationsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


