/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type {
  EmailForm
} from '.././model';

import { customFetch } from '../../custom-fetch';

export type postApiV1ContactPostContactFormResponse200 = {
  data: boolean
  status: 200
}

export type postApiV1ContactPostContactFormResponse500 = {
  data: void
  status: 500
}
    
export type postApiV1ContactPostContactFormResponseComposite = postApiV1ContactPostContactFormResponse200 | postApiV1ContactPostContactFormResponse500;
    
export type postApiV1ContactPostContactFormResponse = postApiV1ContactPostContactFormResponseComposite & {
  headers: Headers;
}

export const getPostApiV1ContactPostContactFormUrl = () => {


  

  return `http://localhost:23142/api/v1/contact/postContactForm`
}

export const postApiV1ContactPostContactForm = async (emailForm: EmailForm, options?: RequestInit): Promise<postApiV1ContactPostContactFormResponse> => {
  
  return customFetch<postApiV1ContactPostContactFormResponse>(getPostApiV1ContactPostContactFormUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailForm,)
  }
);}


