/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Engage API
 * You can find out more about the Umbraco Engage API in [the documentation](https://docs.umbraco.com/umbraco-engage/developers/headless/using-the-marketing-api).
 * OpenAPI spec version: v1
 */
import type {
  NotPermittedDueToLicenseResult,
  PageEventRequestModel,
  RemotePageViewClientRequestModel,
  RemotePageViewResponseModel,
  RemotePageViewServerRequestModel,
  StatusCodeResult
} from '.././model';

import { customFetch } from '../../custom-fetch';

export type postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponse200 = {
  data: StatusCodeResult
  status: 200
}

export type postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponse500 = {
  data: StatusCodeResult
  status: 500
}
    
export type postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponseComposite = postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponse200 | postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponse500;
    
export type postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponse = postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponseComposite & {
  headers: Headers;
}

export const getPostUmbracoEngageApiV1AnalyticsPageeventTrackpageeventUrl = () => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/analytics/pageevent/trackpageevent`
}

export const postUmbracoEngageApiV1AnalyticsPageeventTrackpageevent = async (pageEventRequestModel: PageEventRequestModel, options?: RequestInit): Promise<postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponse> => {
  
  return customFetch<postUmbracoEngageApiV1AnalyticsPageeventTrackpageeventResponse>(getPostUmbracoEngageApiV1AnalyticsPageeventTrackpageeventUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pageEventRequestModel,)
  }
);}


export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse200 = {
  data: RemotePageViewResponseModel
  status: 200
}

export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse402 = {
  data: NotPermittedDueToLicenseResult
  status: 402
}

export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse500 = {
  data: StatusCodeResult
  status: 500
}
    
export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponseComposite = postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse200 | postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse402 | postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse500;
    
export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse = postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponseComposite & {
  headers: Headers;
}

export const getPostUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientUrl = () => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/analytics/pageview/trackpageview/client`
}

export const postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClient = async (remotePageViewClientRequestModel: RemotePageViewClientRequestModel, options?: RequestInit): Promise<postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse> => {
  
  return customFetch<postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientResponse>(getPostUmbracoEngageApiV1AnalyticsPageviewTrackpageviewClientUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      remotePageViewClientRequestModel,)
  }
);}


export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse200 = {
  data: RemotePageViewResponseModel
  status: 200
}

export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse402 = {
  data: NotPermittedDueToLicenseResult
  status: 402
}

export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse500 = {
  data: StatusCodeResult
  status: 500
}
    
export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponseComposite = postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse200 | postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse402 | postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse500;
    
export type postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse = postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponseComposite & {
  headers: Headers;
}

export const getPostUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerUrl = () => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/analytics/pageview/trackpageview/server`
}

export const postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServer = async (remotePageViewServerRequestModel: RemotePageViewServerRequestModel, options?: RequestInit): Promise<postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse> => {
  
  return customFetch<postUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerResponse>(getPostUmbracoEngageApiV1AnalyticsPageviewTrackpageviewServerUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      remotePageViewServerRequestModel,)
  }
);}


