/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type {
  GetContent20400,
  GetContent20404,
  GetContent20Params,
  GetContent400,
  GetContent404,
  GetContentItem401,
  GetContentItem403,
  GetContentItemById20401,
  GetContentItemById20403,
  GetContentItemById20404,
  GetContentItemById20Params,
  GetContentItemById401,
  GetContentItemById403,
  GetContentItemById404,
  GetContentItemByIdParams,
  GetContentItemByPath20401,
  GetContentItemByPath20403,
  GetContentItemByPath20404,
  GetContentItemByPath20Params,
  GetContentItemByPath401,
  GetContentItemByPath403,
  GetContentItemByPath404,
  GetContentItemByPathParams,
  GetContentItemParams,
  GetContentItems20401,
  GetContentItems20403,
  GetContentItems20Params,
  GetContentParams,
  GetMedia20400,
  GetMedia20Params,
  GetMedia400,
  GetMediaItemById20404,
  GetMediaItemById20Params,
  GetMediaItemById404,
  GetMediaItemByIdParams,
  GetMediaItemByPath20404,
  GetMediaItemByPath20Params,
  GetMediaItemByPath404,
  GetMediaItemByPathParams,
  GetMediaItemParams,
  GetMediaItems20Params,
  GetMediaParams,
  IApiContentResponseModel,
  IApiMediaWithCropsResponseModel,
  PagedIApiContentResponseModel,
  PagedIApiMediaWithCropsResponseModel
} from './model';

/**
 * @deprecated
 */
export type getContentResponse200 = {
  data: PagedIApiContentResponseModel
  status: 200
}

export type getContentResponse400 = {
  data: GetContent400
  status: 400
}

export type getContentResponse404 = {
  data: GetContent404
  status: 404
}
    
export type getContentResponseComposite = getContentResponse200 | getContentResponse400 | getContentResponse404;
    
export type getContentResponse = getContentResponseComposite & {
  headers: Headers;
}

export const getGetContentUrl = (params?: GetContentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/content?${stringifiedParams}` : `/umbraco/delivery/api/v1/content`
}

export const getContent = async (params?: GetContentParams, options?: RequestInit): Promise<getContentResponse> => {
  
  const res = await fetch(getGetContentUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContentResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContentResponse
}



export type getContent20Response200 = {
  data: PagedIApiContentResponseModel
  status: 200
}

export type getContent20Response400 = {
  data: GetContent20400
  status: 400
}

export type getContent20Response404 = {
  data: GetContent20404
  status: 404
}
    
export type getContent20ResponseComposite = getContent20Response200 | getContent20Response400 | getContent20Response404;
    
export type getContent20Response = getContent20ResponseComposite & {
  headers: Headers;
}

export const getGetContent20Url = (params?: GetContent20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/content?${stringifiedParams}` : `/umbraco/delivery/api/v2/content`
}

export const getContent20 = async (params?: GetContent20Params, options?: RequestInit): Promise<getContent20Response> => {
  const res = await fetch(getGetContent20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContent20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContent20Response
}



/**
 * @deprecated
 */
export type getContentItemResponse200 = {
  data: IApiContentResponseModel[]
  status: 200
}

export type getContentItemResponse401 = {
  data: GetContentItem401
  status: 401
}

export type getContentItemResponse403 = {
  data: GetContentItem403
  status: 403
}
    
export type getContentItemResponseComposite = getContentItemResponse200 | getContentItemResponse401 | getContentItemResponse403;
    
export type getContentItemResponse = getContentItemResponseComposite & {
  headers: Headers;
}

export const getGetContentItemUrl = (params?: GetContentItemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/content/item?${stringifiedParams}` : `/umbraco/delivery/api/v1/content/item`
}

export const getContentItem = async (params?: GetContentItemParams, options?: RequestInit): Promise<getContentItemResponse> => {
  
  const res = await fetch(getGetContentItemUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContentItemResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContentItemResponse
}



/**
 * @deprecated
 */
export type getContentItemByPathResponse200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemByPathResponse401 = {
  data: GetContentItemByPath401
  status: 401
}

export type getContentItemByPathResponse403 = {
  data: GetContentItemByPath403
  status: 403
}

export type getContentItemByPathResponse404 = {
  data: GetContentItemByPath404
  status: 404
}
    
export type getContentItemByPathResponseComposite = getContentItemByPathResponse200 | getContentItemByPathResponse401 | getContentItemByPathResponse403 | getContentItemByPathResponse404;
    
export type getContentItemByPathResponse = getContentItemByPathResponseComposite & {
  headers: Headers;
}

export const getGetContentItemByPathUrl = (path: string,
    params?: GetContentItemByPathParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/content/item/${path}?${stringifiedParams}` : `/umbraco/delivery/api/v1/content/item/${path}`
}

export const getContentItemByPath = async (path: string,
    params?: GetContentItemByPathParams, options?: RequestInit): Promise<getContentItemByPathResponse> => {
  
  const res = await fetch(getGetContentItemByPathUrl(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContentItemByPathResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContentItemByPathResponse
}



export type getContentItemByPath20Response200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemByPath20Response401 = {
  data: GetContentItemByPath20401
  status: 401
}

export type getContentItemByPath20Response403 = {
  data: GetContentItemByPath20403
  status: 403
}

export type getContentItemByPath20Response404 = {
  data: GetContentItemByPath20404
  status: 404
}
    
export type getContentItemByPath20ResponseComposite = getContentItemByPath20Response200 | getContentItemByPath20Response401 | getContentItemByPath20Response403 | getContentItemByPath20Response404;
    
export type getContentItemByPath20Response = getContentItemByPath20ResponseComposite & {
  headers: Headers;
}

export const getGetContentItemByPath20Url = (path: string,
    params?: GetContentItemByPath20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/content/item/${path}?${stringifiedParams}` : `/umbraco/delivery/api/v2/content/item/${path}`
}

export const getContentItemByPath20 = async (path: string,
    params?: GetContentItemByPath20Params, options?: RequestInit): Promise<getContentItemByPath20Response> => {
  
      console.log(getGetContentItemByPath20Url(path,params))

  const res = await fetch(getGetContentItemByPath20Url(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContentItemByPath20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContentItemByPath20Response
}



/**
 * @deprecated
 */
export type getContentItemByIdResponse200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemByIdResponse401 = {
  data: GetContentItemById401
  status: 401
}

export type getContentItemByIdResponse403 = {
  data: GetContentItemById403
  status: 403
}

export type getContentItemByIdResponse404 = {
  data: GetContentItemById404
  status: 404
}
    
export type getContentItemByIdResponseComposite = getContentItemByIdResponse200 | getContentItemByIdResponse401 | getContentItemByIdResponse403 | getContentItemByIdResponse404;
    
export type getContentItemByIdResponse = getContentItemByIdResponseComposite & {
  headers: Headers;
}

export const getGetContentItemByIdUrl = (id: string,
    params?: GetContentItemByIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/content/item/${id}?${stringifiedParams}` : `/umbraco/delivery/api/v1/content/item/${id}`
}

export const getContentItemById = async (id: string,
    params?: GetContentItemByIdParams, options?: RequestInit): Promise<getContentItemByIdResponse> => {
  
  const res = await fetch(getGetContentItemByIdUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContentItemByIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContentItemByIdResponse
}



export type getContentItemById20Response200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemById20Response401 = {
  data: GetContentItemById20401
  status: 401
}

export type getContentItemById20Response403 = {
  data: GetContentItemById20403
  status: 403
}

export type getContentItemById20Response404 = {
  data: GetContentItemById20404
  status: 404
}
    
export type getContentItemById20ResponseComposite = getContentItemById20Response200 | getContentItemById20Response401 | getContentItemById20Response403 | getContentItemById20Response404;
    
export type getContentItemById20Response = getContentItemById20ResponseComposite & {
  headers: Headers;
}

export const getGetContentItemById20Url = (id: string,
    params?: GetContentItemById20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/content/item/${id}?${stringifiedParams}` : `/umbraco/delivery/api/v2/content/item/${id}`
}

export const getContentItemById20 = async (id: string,
    params?: GetContentItemById20Params, options?: RequestInit): Promise<getContentItemById20Response> => {
  
  const res = await fetch(getGetContentItemById20Url(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContentItemById20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContentItemById20Response
}



export type getContentItems20Response200 = {
  data: IApiContentResponseModel[]
  status: 200
}

export type getContentItems20Response401 = {
  data: GetContentItems20401
  status: 401
}

export type getContentItems20Response403 = {
  data: GetContentItems20403
  status: 403
}
    
export type getContentItems20ResponseComposite = getContentItems20Response200 | getContentItems20Response401 | getContentItems20Response403;
    
export type getContentItems20Response = getContentItems20ResponseComposite & {
  headers: Headers;
}

export const getGetContentItems20Url = (params?: GetContentItems20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/content/items?${stringifiedParams}` : `/umbraco/delivery/api/v2/content/items`
}

export const getContentItems20 = async (params?: GetContentItems20Params, options?: RequestInit): Promise<getContentItems20Response> => {
  
  const res = await fetch(getGetContentItems20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getContentItems20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getContentItems20Response
}



/**
 * @deprecated
 */
export type getMediaResponse200 = {
  data: PagedIApiMediaWithCropsResponseModel
  status: 200
}

export type getMediaResponse400 = {
  data: GetMedia400
  status: 400
}
    
export type getMediaResponseComposite = getMediaResponse200 | getMediaResponse400;
    
export type getMediaResponse = getMediaResponseComposite & {
  headers: Headers;
}

export const getGetMediaUrl = (params?: GetMediaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/media?${stringifiedParams}` : `/umbraco/delivery/api/v1/media`
}

export const getMedia = async (params?: GetMediaParams, options?: RequestInit): Promise<getMediaResponse> => {
  
  const res = await fetch(getGetMediaUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMediaResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMediaResponse
}



export type getMedia20Response200 = {
  data: PagedIApiMediaWithCropsResponseModel
  status: 200
}

export type getMedia20Response400 = {
  data: GetMedia20400
  status: 400
}
    
export type getMedia20ResponseComposite = getMedia20Response200 | getMedia20Response400;
    
export type getMedia20Response = getMedia20ResponseComposite & {
  headers: Headers;
}

export const getGetMedia20Url = (params?: GetMedia20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/media?${stringifiedParams}` : `/umbraco/delivery/api/v2/media`
}

export const getMedia20 = async (params?: GetMedia20Params, options?: RequestInit): Promise<getMedia20Response> => {
  
  const res = await fetch(getGetMedia20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMedia20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMedia20Response
}



/**
 * @deprecated
 */
export type getMediaItemResponse200 = {
  data: IApiMediaWithCropsResponseModel[]
  status: 200
}
    
export type getMediaItemResponseComposite = getMediaItemResponse200;
    
export type getMediaItemResponse = getMediaItemResponseComposite & {
  headers: Headers;
}

export const getGetMediaItemUrl = (params?: GetMediaItemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/media/item?${stringifiedParams}` : `/umbraco/delivery/api/v1/media/item`
}

export const getMediaItem = async (params?: GetMediaItemParams, options?: RequestInit): Promise<getMediaItemResponse> => {
  
  const res = await fetch(getGetMediaItemUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMediaItemResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMediaItemResponse
}



/**
 * @deprecated
 */
export type getMediaItemByPathResponse200 = {
  data: IApiMediaWithCropsResponseModel
  status: 200
}

export type getMediaItemByPathResponse404 = {
  data: GetMediaItemByPath404
  status: 404
}
    
export type getMediaItemByPathResponseComposite = getMediaItemByPathResponse200 | getMediaItemByPathResponse404;
    
export type getMediaItemByPathResponse = getMediaItemByPathResponseComposite & {
  headers: Headers;
}

export const getGetMediaItemByPathUrl = (path: string,
    params?: GetMediaItemByPathParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/media/item/${path}?${stringifiedParams}` : `/umbraco/delivery/api/v1/media/item/${path}`
}

export const getMediaItemByPath = async (path: string,
    params?: GetMediaItemByPathParams, options?: RequestInit): Promise<getMediaItemByPathResponse> => {
  
  const res = await fetch(getGetMediaItemByPathUrl(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMediaItemByPathResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMediaItemByPathResponse
}



export type getMediaItemByPath20Response200 = {
  data: IApiMediaWithCropsResponseModel
  status: 200
}

export type getMediaItemByPath20Response404 = {
  data: GetMediaItemByPath20404
  status: 404
}
    
export type getMediaItemByPath20ResponseComposite = getMediaItemByPath20Response200 | getMediaItemByPath20Response404;
    
export type getMediaItemByPath20Response = getMediaItemByPath20ResponseComposite & {
  headers: Headers;
}

export const getGetMediaItemByPath20Url = (path: string,
    params?: GetMediaItemByPath20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/media/item/${path}?${stringifiedParams}` : `/umbraco/delivery/api/v2/media/item/${path}`
}

export const getMediaItemByPath20 = async (path: string,
    params?: GetMediaItemByPath20Params, options?: RequestInit): Promise<getMediaItemByPath20Response> => {
  
  const res = await fetch(getGetMediaItemByPath20Url(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMediaItemByPath20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMediaItemByPath20Response
}



/**
 * @deprecated
 */
export type getMediaItemByIdResponse200 = {
  data: IApiMediaWithCropsResponseModel
  status: 200
}

export type getMediaItemByIdResponse404 = {
  data: GetMediaItemById404
  status: 404
}
    
export type getMediaItemByIdResponseComposite = getMediaItemByIdResponse200 | getMediaItemByIdResponse404;
    
export type getMediaItemByIdResponse = getMediaItemByIdResponseComposite & {
  headers: Headers;
}

export const getGetMediaItemByIdUrl = (id: string,
    params?: GetMediaItemByIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v1/media/item/${id}?${stringifiedParams}` : `/umbraco/delivery/api/v1/media/item/${id}`
}

export const getMediaItemById = async (id: string,
    params?: GetMediaItemByIdParams, options?: RequestInit): Promise<getMediaItemByIdResponse> => {
  
  const res = await fetch(getGetMediaItemByIdUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMediaItemByIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMediaItemByIdResponse
}



export type getMediaItemById20Response200 = {
  data: IApiMediaWithCropsResponseModel
  status: 200
}

export type getMediaItemById20Response404 = {
  data: GetMediaItemById20404
  status: 404
}
    
export type getMediaItemById20ResponseComposite = getMediaItemById20Response200 | getMediaItemById20Response404;
    
export type getMediaItemById20Response = getMediaItemById20ResponseComposite & {
  headers: Headers;
}

export const getGetMediaItemById20Url = (id: string,
    params?: GetMediaItemById20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/media/item/${id}?${stringifiedParams}` : `/umbraco/delivery/api/v2/media/item/${id}`
}

export const getMediaItemById20 = async (id: string,
    params?: GetMediaItemById20Params, options?: RequestInit): Promise<getMediaItemById20Response> => {
  
  const res = await fetch(getGetMediaItemById20Url(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMediaItemById20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMediaItemById20Response
}



export type getMediaItems20Response200 = {
  data: IApiMediaWithCropsResponseModel[]
  status: 200
}
    
export type getMediaItems20ResponseComposite = getMediaItems20Response200;
    
export type getMediaItems20Response = getMediaItems20ResponseComposite & {
  headers: Headers;
}

export const getGetMediaItems20Url = (params?: GetMediaItems20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/umbraco/delivery/api/v2/media/items?${stringifiedParams}` : `/umbraco/delivery/api/v2/media/items`
}

export const getMediaItems20 = async (params?: GetMediaItems20Params, options?: RequestInit): Promise<getMediaItems20Response> => {
  
  const res = await fetch(getGetMediaItems20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getMediaItems20Response['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getMediaItems20Response
}
