// This file is auto-generated by @hey-api/openapi-ts

export type ApiBlockGridAreaModel = {
    alias?: string;
    rowSpan?: number;
    columnSpan?: number;
    items?: Array<ApiBlockGridItemModel>;
};

export type ApiBlockGridItemModel = ApiBlockItemModel & {
    rowSpan?: number;
    columnSpan?: number;
    areaGridColumns?: number;
    areas?: Array<ApiBlockGridAreaModel>;
};

export type ApiBlockItemModel = {
    content?: IApiElementModel;
    settings?: IApiElementModel;
};

export type ApiBlockListModel = {
    items?: Array<(ApiBlockItemModel | ApiBlockGridItemModel)>;
};

export type ApiLinkModel = {
    readonly url?: (string) | null;
    readonly queryString?: (string) | null;
    readonly title?: (string) | null;
    readonly target?: (string) | null;
    readonly destinationId?: (string) | null;
    readonly destinationType?: (string) | null;
    route?: IApiContentRouteModel;
    linkType?: LinkTypeModel;
};

export type ArticleContentModel = IApiContentModelBase & {
    properties?: ArticlePropertiesModel;
};

export type ArticleContentResponseModel = IApiContentResponseModelBase & ArticleContentModel;

export type ArticleControlsContentModel = IApiContentModelBase & {
    properties?: ArticleControlsPropertiesModel;
};

export type ArticleControlsContentResponseModel = IApiContentResponseModelBase & ArticleControlsContentModel;

export type ArticleControlsPropertiesModel = {
    articleDate?: (Date) | null;
    author?: Array<IApiContentModel> | null;
    categories?: Array<IApiContentModel> | null;
};

export type ArticleListContentModel = IApiContentModelBase & {
    properties?: ArticleListPropertiesModel;
};

export type ArticleListContentResponseModel = IApiContentResponseModelBase & ArticleListContentModel;

export type ArticleListPropertiesModel = ListPageSettingsPropertiesModel & VisibilityControlsPropertiesModel & SEocontrolsPropertiesModel & MainImageControlsPropertiesModel & HeaderControlsPropertiesModel & ContentControlsPropertiesModel;

export type ArticlePropertiesModel = ArticleControlsPropertiesModel & ContentControlsPropertiesModel & HeaderControlsPropertiesModel & MainImageControlsPropertiesModel & SEocontrolsPropertiesModel & VisibilityControlsPropertiesModel & ListPageSettingsPropertiesModel;

export type AuthorContentModel = IApiContentModelBase & {
    properties?: AuthorPropertiesModel;
};

export type AuthorContentResponseModel = IApiContentResponseModelBase & AuthorContentModel;

export type AuthorListContentModel = IApiContentModelBase & {
    properties?: AuthorListPropertiesModel;
};

export type AuthorListContentResponseModel = IApiContentResponseModelBase & AuthorListContentModel;

export type AuthorListPropertiesModel = VisibilityControlsPropertiesModel & SEocontrolsPropertiesModel & MainImageControlsPropertiesModel & HeaderControlsPropertiesModel & ContentControlsPropertiesModel;

export type AuthorPropertiesModel = ContentControlsPropertiesModel & HeaderControlsPropertiesModel & MainImageControlsPropertiesModel & SEocontrolsPropertiesModel & VisibilityControlsPropertiesModel;

export type CategoryContentModel = IApiContentModelBase & {
    properties?: CategoryPropertiesModel;
};

export type CategoryContentResponseModel = IApiContentResponseModelBase & CategoryContentModel;

export type CategoryListContentModel = IApiContentModelBase & {
    properties?: CategoryListPropertiesModel;
};

export type CategoryListContentResponseModel = IApiContentResponseModelBase & CategoryListContentModel;

export type CategoryListPropertiesModel = VisibilityControlsPropertiesModel;

export type CategoryPropertiesModel = {
    [key: string]: unknown;
};

export type CodeSnippetRowElementModel = IApiElementModelBase & {
    properties?: CodeSnippetRowPropertiesModel;
};

export type CodeSnippetRowPropertiesModel = {
    title?: (string) | null;
    code?: (string) | null;
};

export type CodeSnippetRowSettingsElementModel = IApiElementModelBase & {
    properties?: CodeSnippetRowSettingsPropertiesModel;
};

export type CodeSnippetRowSettingsPropertiesModel = HidePropertyPropertiesModel & SpacingPropertiesPropertiesModel;

export type ContactContentModel = IApiContentModelBase & {
    properties?: ContactPropertiesModel;
};

export type ContactContentResponseModel = IApiContentResponseModelBase & ContactContentModel;

export type ContactFormControlsContentModel = IApiContentModelBase & {
    properties?: ContactFormControlsPropertiesModel;
};

export type ContactFormControlsContentResponseModel = IApiContentResponseModelBase & ContactFormControlsContentModel;

export type ContactFormControlsPropertiesModel = {
    instructionMessage?: RichTextModel;
    successMessage?: RichTextModel;
    errorMessage?: RichTextModel;
};

export type ContactPropertiesModel = VisibilityControlsPropertiesModel & ContactFormControlsPropertiesModel & HeaderControlsPropertiesModel & MainImageControlsPropertiesModel & SEocontrolsPropertiesModel;

export type ContentContentModel = IApiContentModelBase & {
    properties?: ContentPropertiesModel;
};

export type ContentContentResponseModel = IApiContentResponseModelBase & ContentContentModel;

export type ContentControlsContentModel = IApiContentModelBase & {
    properties?: ContentControlsPropertiesModel;
};

export type ContentControlsContentResponseModel = IApiContentResponseModelBase & ContentControlsContentModel;

export type ContentControlsPropertiesModel = {
    contentRows?: ApiBlockListModel;
};

export type ContentPropertiesModel = SEocontrolsPropertiesModel & MainImageControlsPropertiesModel & HeaderControlsPropertiesModel & ContentControlsPropertiesModel & VisibilityControlsPropertiesModel;

export type ErrorContentModel = IApiContentModelBase & {
    properties?: ErrorPropertiesModel;
};

export type ErrorContentResponseModel = IApiContentResponseModelBase & ErrorContentModel;

export type ErrorPropertiesModel = VisibilityControlsPropertiesModel & ContentControlsPropertiesModel & HeaderControlsPropertiesModel & MainImageControlsPropertiesModel & SEocontrolsPropertiesModel;

export type FooterControlsContentModel = IApiContentModelBase & {
    properties?: FooterControlsPropertiesModel;
};

export type FooterControlsContentResponseModel = IApiContentResponseModelBase & FooterControlsContentModel;

export type FooterControlsPropertiesModel = {
    socialIconLinks?: ApiBlockListModel;
};

export type HeaderControlsContentModel = IApiContentModelBase & {
    properties?: HeaderControlsPropertiesModel;
};

export type HeaderControlsContentResponseModel = IApiContentResponseModelBase & HeaderControlsContentModel;

export type HeaderControlsPropertiesModel = {
    title?: (string) | null;
    subtitle?: (string) | null;
};

export type HidePropertyElementModel = IApiElementModelBase & {
    properties?: HidePropertyPropertiesModel;
};

export type HidePropertyPropertiesModel = {
    hide?: (boolean) | null;
};

export type HomeContentModel = IApiContentModelBase & {
    properties?: HomePropertiesModel;
};

export type HomeContentResponseModel = IApiContentResponseModelBase & HomeContentModel;

export type HomePropertiesModel = SEocontrolsPropertiesModel & MainImageControlsPropertiesModel & HeaderControlsPropertiesModel & ContentControlsPropertiesModel & FooterControlsPropertiesModel;

export type HttpValidationProblemDetails = ProblemDetails & {
    errors?: {
        [key: string]: Array<(string)>;
    };
    [key: string]: (unknown | string) | undefined;
};

export type IApiContentModel = ArticleControlsContentModel | ContentControlsContentModel | HeaderControlsContentModel | MainImageControlsContentModel | SEocontrolsContentModel | VisibilityControlsContentModel | ArticleContentModel | ArticleListContentModel | AuthorContentModel | AuthorListContentModel | CategoryContentModel | CategoryListContentModel | ContactFormControlsContentModel | ContactContentModel | ContentContentModel | ErrorContentModel | FooterControlsContentModel | HomeContentModel | SearchContentModel | XMlsitemapContentModel | LoginContentModel;

export type IApiContentModelBase = IApiElementModelBase & {
    readonly id?: string;
    readonly contentType: string;
    readonly name?: (string) | null;
    readonly createDate?: Date;
    readonly updateDate?: Date;
    route?: IApiContentRouteModel;
};

export type IApiContentResponseModel = ArticleControlsContentResponseModel | ContentControlsContentResponseModel | HeaderControlsContentResponseModel | MainImageControlsContentResponseModel | SEocontrolsContentResponseModel | VisibilityControlsContentResponseModel | ArticleContentResponseModel | ArticleListContentResponseModel | AuthorContentResponseModel | AuthorListContentResponseModel | CategoryContentResponseModel | CategoryListContentResponseModel | ContactFormControlsContentResponseModel | ContactContentResponseModel | ContentContentResponseModel | ErrorContentResponseModel | FooterControlsContentResponseModel | HomeContentResponseModel | SearchContentResponseModel | XMlsitemapContentResponseModel | LoginContentResponseModel;

export type IApiContentResponseModelBase = IApiContentModelBase & {
    readonly id?: string;
    readonly contentType: string;
    readonly name?: (string) | null;
    readonly createDate?: Date;
    readonly updateDate?: Date;
    route?: IApiContentRouteModel;
    readonly cultures?: {
        [key: string]: IApiContentRouteModel;
    };
};

export type IApiContentRouteModel = {
    readonly path?: string;
    startItem?: IApiContentStartItemModel;
};

export type IApiContentStartItemModel = {
    readonly id?: string;
    readonly path?: string;
};

export type IApiElementModel = ListPageSettingsElementModel | CodeSnippetRowElementModel | HidePropertyElementModel | SpacingPropertiesElementModel | CodeSnippetRowSettingsElementModel | IconLinkRowElementModel | IconLinkRowSettingsElementModel | ImageCarouselRowElementModel | ImageCarouselRowSettingsElementModel | ImageRowElementModel | ImageRowSettingsElementModel | LatestArticlesRowSettingsElementModel | LatestArticlesRowElementModel | RichTextRowElementModel | RichTextRowSettingsElementModel | VideoRowElementModel | VideoRowSettingsElementModel;

export type IApiElementModelBase = {
    readonly id?: string;
    readonly contentType: string;
};

export type IApiMediaWithCropsModel = {
    readonly id?: string;
    readonly name?: string;
    readonly mediaType?: string;
    readonly url?: string;
    readonly extension?: (string) | null;
    readonly width?: (number) | null;
    readonly height?: (number) | null;
    readonly bytes?: (number) | null;
    readonly properties?: {
        [key: string]: unknown;
    };
    focalPoint?: ImageFocalPointModel;
    readonly crops?: Array<ImageCropModel> | null;
};

export type IApiMediaWithCropsResponseModel = {
    readonly id?: string;
    readonly name?: string;
    readonly mediaType?: string;
    readonly url?: string;
    readonly extension?: (string) | null;
    readonly width?: (number) | null;
    readonly height?: (number) | null;
    readonly bytes?: (number) | null;
    readonly properties?: {
        [key: string]: unknown;
    };
    focalPoint?: ImageFocalPointModel;
    readonly crops?: Array<ImageCropModel> | null;
    readonly path?: string;
    readonly createDate?: Date;
    readonly updateDate?: Date;
};

export type IconLinkRowElementModel = IApiElementModelBase & {
    properties?: IconLinkRowPropertiesModel;
};

export type IconLinkRowPropertiesModel = {
    icon?: Array<IApiMediaWithCropsModel> | null;
    link?: Array<ApiLinkModel> | null;
};

export type IconLinkRowSettingsElementModel = IApiElementModelBase & {
    properties?: IconLinkRowSettingsPropertiesModel;
};

export type IconLinkRowSettingsPropertiesModel = HidePropertyPropertiesModel;

export type ImageCarouselRowElementModel = IApiElementModelBase & {
    properties?: ImageCarouselRowPropertiesModel;
};

export type ImageCarouselRowPropertiesModel = {
    images?: Array<IApiMediaWithCropsModel> | null;
};

export type ImageCarouselRowSettingsElementModel = IApiElementModelBase & {
    properties?: ImageCarouselRowSettingsPropertiesModel;
};

export type ImageCarouselRowSettingsPropertiesModel = HidePropertyPropertiesModel & SpacingPropertiesPropertiesModel;

export type ImageCropCoordinatesModel = {
    x1?: number;
    y1?: number;
    x2?: number;
    y2?: number;
};

export type ImageCropModel = {
    alias?: (string) | null;
    width?: number;
    height?: number;
    coordinates?: ImageCropCoordinatesModel;
};

export type ImageFocalPointModel = {
    left?: number;
    top?: number;
};

export type ImageRowElementModel = IApiElementModelBase & {
    properties?: ImageRowPropertiesModel;
};

export type ImageRowPropertiesModel = {
    image?: Array<IApiMediaWithCropsModel> | null;
    caption?: (string) | null;
};

export type ImageRowSettingsElementModel = IApiElementModelBase & {
    properties?: ImageRowSettingsPropertiesModel;
};

export type ImageRowSettingsPropertiesModel = SpacingPropertiesPropertiesModel & HidePropertyPropertiesModel;

export type LatestArticlesRowElementModel = IApiElementModelBase & {
    properties?: LatestArticlesRowPropertiesModel;
};

export type LatestArticlesRowPropertiesModel = {
    articleList?: IApiContentModel;
    pageSize?: (number) | null;
    showPagination?: (boolean) | null;
};

export type LatestArticlesRowSettingsElementModel = IApiElementModelBase & {
    properties?: LatestArticlesRowSettingsPropertiesModel;
};

export type LatestArticlesRowSettingsPropertiesModel = HidePropertyPropertiesModel & SpacingPropertiesPropertiesModel;

export enum LinkTypeModel {
    CONTENT = 'Content',
    MEDIA = 'Media',
    EXTERNAL = 'External'
}

export type ListPageSettingsElementModel = IApiElementModelBase & {
    properties?: ListPageSettingsPropertiesModel;
};

export type ListPageSettingsPropertiesModel = {
    [key: string]: unknown;
};

export type LoginContentModel = IApiContentModelBase & {
    properties?: LoginPropertiesModel;
};

export type LoginContentResponseModel = IApiContentResponseModelBase & LoginContentModel;

export type LoginPropertiesModel = {
    [key: string]: unknown;
};

export type MainImageControlsContentModel = IApiContentModelBase & {
    properties?: MainImageControlsPropertiesModel;
};

export type MainImageControlsContentResponseModel = IApiContentResponseModelBase & MainImageControlsContentModel;

export type MainImageControlsPropertiesModel = {
    mainImage?: Array<IApiMediaWithCropsModel> | null;
};

export type PagedIApiContentResponseModel = {
    total: number;
    items: Array<IApiContentResponseModel>;
};

export type PagedIApiMediaWithCropsResponseModel = {
    total: number;
    items: Array<IApiMediaWithCropsResponseModel>;
};

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type RichTextModel = {
    markup: string;
    blocks: Array<(ApiBlockItemModel | ApiBlockGridItemModel)>;
};

export type RichTextRowElementModel = IApiElementModelBase & {
    properties?: RichTextRowPropertiesModel;
};

export type RichTextRowPropertiesModel = {
    content?: RichTextModel;
};

export type RichTextRowSettingsElementModel = IApiElementModelBase & {
    properties?: RichTextRowSettingsPropertiesModel;
};

export type RichTextRowSettingsPropertiesModel = SpacingPropertiesPropertiesModel & HidePropertyPropertiesModel;

export type SearchContentModel = IApiContentModelBase & {
    properties?: SearchPropertiesModel;
};

export type SearchContentResponseModel = IApiContentResponseModelBase & SearchContentModel;

export type SearchPropertiesModel = VisibilityControlsPropertiesModel & HeaderControlsPropertiesModel & MainImageControlsPropertiesModel & SEocontrolsPropertiesModel;

export type SEocontrolsContentModel = IApiContentModelBase & {
    properties?: SEocontrolsPropertiesModel;
};

export type SEocontrolsContentResponseModel = IApiContentResponseModelBase & SEocontrolsContentModel;

export type SEocontrolsPropertiesModel = {
    metaName?: (string) | null;
    metaDescription?: (string) | null;
    metaKeywords?: Array<(string)> | null;
    isIndexable?: (boolean) | null;
    isFollowable?: (boolean) | null;
};

export type SpacingPropertiesElementModel = IApiElementModelBase & {
    properties?: SpacingPropertiesPropertiesModel;
};

export type SpacingPropertiesPropertiesModel = {
    paddingTop?: (string) | null;
    paddingBottom?: (string) | null;
    paddingLeft?: (string) | null;
    paddingRight?: (string) | null;
    marginTop?: (string) | null;
    marginBottom?: (string) | null;
    marginLeft?: (string) | null;
    marginRight?: (string) | null;
};

export type VideoRowElementModel = IApiElementModelBase & {
    properties?: VideoRowPropertiesModel;
};

export type VideoRowPropertiesModel = {
    videoUrl?: (string) | null;
    caption?: (string) | null;
};

export type VideoRowSettingsElementModel = IApiElementModelBase & {
    properties?: VideoRowSettingsPropertiesModel;
};

export type VideoRowSettingsPropertiesModel = HidePropertyPropertiesModel & SpacingPropertiesPropertiesModel;

export type VisibilityControlsContentModel = IApiContentModelBase & {
    properties?: VisibilityControlsPropertiesModel;
};

export type VisibilityControlsContentResponseModel = IApiContentResponseModelBase & VisibilityControlsContentModel;

export type VisibilityControlsPropertiesModel = {
    hideFromTopNavigation?: (boolean) | null;
    umbracoNaviHide?: (boolean) | null;
    hideFromXMLSitemap?: (boolean) | null;
};

export type XMlsitemapContentModel = IApiContentModelBase & {
    properties?: XMlsitemapPropertiesModel;
};

export type XMlsitemapContentResponseModel = IApiContentResponseModelBase & XMlsitemapContentModel;

export type XMlsitemapPropertiesModel = VisibilityControlsPropertiesModel;

export type GetContentData = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fetch?: string;
    /**
     * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    filter?: Array<(string)>;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * Specifies the number of found content items to skip. Use this to control pagination of the response.
     */
    skip?: number;
    /**
     * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    sort?: Array<(string)>;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
    /**
     * Specifies the number of found content items to take. Use this to control pagination of the response.
     */
    take?: number;
};

export type GetContentResponse = (PagedIApiContentResponseModel);

export type GetContent20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fetch?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    /**
     * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    filter?: Array<(string)>;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * Specifies the number of found content items to skip. Use this to control pagination of the response.
     */
    skip?: number;
    /**
     * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    sort?: Array<(string)>;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
    /**
     * Specifies the number of found content items to take. Use this to control pagination of the response.
     */
    take?: number;
};

export type GetContent20Response = (PagedIApiContentResponseModel);

export type GetContentItemData = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    id?: Array<(string)>;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type GetContentItemResponse = (Array<IApiContentResponseModel>);

export type GetContentItemByPathData = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    path: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type GetContentItemByPathResponse = (IApiContentResponseModel);

export type GetContentItemByPath20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    path: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type GetContentItemByPath20Response = (IApiContentResponseModel);

export type GetContentItemByIdData = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    id: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type GetContentItemByIdResponse = (IApiContentResponseModel);

export type GetContentItemById20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    id: string;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type GetContentItemById20Response = (IApiContentResponseModel);

export type GetContentItems20Data = {
    /**
     * Defines the language to return. Use this when querying language variant content items.
     */
    acceptLanguage?: string;
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
     */
    externalVisitorId?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    /**
     * Use this to override the default visitor segmenting behavior (i.e. Personalization and/or A/B Testing) when querying segment variant content items
     */
    forcedSegment?: string;
    id?: Array<(string)>;
    /**
     * Whether to request draft content.
     */
    preview?: boolean;
    /**
     * URL segment or GUID of a root content item.
     */
    startItem?: string;
};

export type GetContentItems20Response = (Array<IApiContentResponseModel>);

export type GetMediaData = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    fetch?: string;
    /**
     * Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    filter?: Array<(string)>;
    /**
     * Specifies the number of found media items to skip. Use this to control pagination of the response.
     */
    skip?: number;
    /**
     * Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    sort?: Array<(string)>;
    /**
     * Specifies the number of found media items to take. Use this to control pagination of the response.
     */
    take?: number;
};

export type GetMediaResponse = (PagedIApiMediaWithCropsResponseModel);

export type GetMedia20Data = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    fetch?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    /**
     * Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    filter?: Array<(string)>;
    /**
     * Specifies the number of found media items to skip. Use this to control pagination of the response.
     */
    skip?: number;
    /**
     * Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    sort?: Array<(string)>;
    /**
     * Specifies the number of found media items to take. Use this to control pagination of the response.
     */
    take?: number;
};

export type GetMedia20Response = (PagedIApiMediaWithCropsResponseModel);

export type GetMediaItemData = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    id?: Array<(string)>;
};

export type GetMediaItemResponse = (Array<IApiMediaWithCropsResponseModel>);

export type GetMediaItemByPathData = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    path: string;
};

export type GetMediaItemByPathResponse = (IApiMediaWithCropsResponseModel);

export type GetMediaItemByPath20Data = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    path: string;
};

export type GetMediaItemByPath20Response = (IApiMediaWithCropsResponseModel);

export type GetMediaItemByIdData = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    id: string;
};

export type GetMediaItemByIdResponse = (IApiMediaWithCropsResponseModel);

export type GetMediaItemById20Data = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    id: string;
};

export type GetMediaItemById20Response = (IApiMediaWithCropsResponseModel);

export type GetMediaItems20Data = {
    /**
     * API key specified through configuration to authorize access to the API.
     */
    apiKey?: string;
    /**
     * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    expand?: string;
    /**
     * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
     */
    fields?: string;
    id?: Array<(string)>;
};

export type GetMediaItems20Response = (Array<IApiMediaWithCropsResponseModel>);

export type GetMediaResponseTransformer = (data: any) => Promise<GetMediaResponse>;

export type PagedIApiMediaWithCropsResponseModelModelResponseTransformer = (data: any) => PagedIApiMediaWithCropsResponseModel;

export type IApiMediaWithCropsResponseModelModelResponseTransformer = (data: any) => IApiMediaWithCropsResponseModel;

export const IApiMediaWithCropsResponseModelModelResponseTransformer: IApiMediaWithCropsResponseModelModelResponseTransformer = data => {
    if (data?.createDate) {
        data.createDate = new Date(data.createDate);
    }
    if (data?.updateDate) {
        data.updateDate = new Date(data.updateDate);
    }
    return data;
};

export const PagedIApiMediaWithCropsResponseModelModelResponseTransformer: PagedIApiMediaWithCropsResponseModelModelResponseTransformer = data => {
    if (Array.isArray(data?.items)) {
        data.items.forEach(IApiMediaWithCropsResponseModelModelResponseTransformer);
    }
    return data;
};

export const GetMediaResponseTransformer: GetMediaResponseTransformer = async (data) => {
    PagedIApiMediaWithCropsResponseModelModelResponseTransformer(data);
    return data;
};

export type GetMedia20ResponseTransformer = (data: any) => Promise<GetMedia20Response>;

export const GetMedia20ResponseTransformer: GetMedia20ResponseTransformer = async (data) => {
    PagedIApiMediaWithCropsResponseModelModelResponseTransformer(data);
    return data;
};

export type GetMediaItemResponseTransformer = (data: any) => Promise<GetMediaItemResponse>;

export const GetMediaItemResponseTransformer: GetMediaItemResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(IApiMediaWithCropsResponseModelModelResponseTransformer);
    }
    return data;
};

export type GetMediaItemByPathResponseTransformer = (data: any) => Promise<GetMediaItemByPathResponse>;

export const GetMediaItemByPathResponseTransformer: GetMediaItemByPathResponseTransformer = async (data) => {
    IApiMediaWithCropsResponseModelModelResponseTransformer(data);
    return data;
};

export type GetMediaItemByPath20ResponseTransformer = (data: any) => Promise<GetMediaItemByPath20Response>;

export const GetMediaItemByPath20ResponseTransformer: GetMediaItemByPath20ResponseTransformer = async (data) => {
    IApiMediaWithCropsResponseModelModelResponseTransformer(data);
    return data;
};

export type GetMediaItemByIdResponseTransformer = (data: any) => Promise<GetMediaItemByIdResponse>;

export const GetMediaItemByIdResponseTransformer: GetMediaItemByIdResponseTransformer = async (data) => {
    IApiMediaWithCropsResponseModelModelResponseTransformer(data);
    return data;
};

export type GetMediaItemById20ResponseTransformer = (data: any) => Promise<GetMediaItemById20Response>;

export const GetMediaItemById20ResponseTransformer: GetMediaItemById20ResponseTransformer = async (data) => {
    IApiMediaWithCropsResponseModelModelResponseTransformer(data);
    return data;
};

export type GetMediaItems20ResponseTransformer = (data: any) => Promise<GetMediaItems20Response>;

export const GetMediaItems20ResponseTransformer: GetMediaItems20ResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(IApiMediaWithCropsResponseModelModelResponseTransformer);
    }
    return data;
};