/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Engage API
 * You can find out more about the Umbraco Engage API in [the documentation](https://docs.umbraco.com/umbraco-engage/developers/headless/using-the-marketing-api).
 * OpenAPI spec version: v1
 */
import type {
  SegmentedContentResponseModel
} from '.././model';

import { customFetch } from '../../custom-fetch';

export type getUmbracoEngageApiV1SegmentationContentActivesegmentsPathResponse200 = {
  data: SegmentedContentResponseModel
  status: 200
}
    
export type getUmbracoEngageApiV1SegmentationContentActivesegmentsPathResponseComposite = getUmbracoEngageApiV1SegmentationContentActivesegmentsPathResponse200;
    
export type getUmbracoEngageApiV1SegmentationContentActivesegmentsPathResponse = getUmbracoEngageApiV1SegmentationContentActivesegmentsPathResponseComposite & {
  headers: Headers;
}

export const getGetUmbracoEngageApiV1SegmentationContentActivesegmentsPathUrl = (path: string,) => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/segmentation/content/activesegments/${path}`
}

export const getUmbracoEngageApiV1SegmentationContentActivesegmentsPath = async (path: string, options?: RequestInit): Promise<getUmbracoEngageApiV1SegmentationContentActivesegmentsPathResponse> => {
  
  return customFetch<getUmbracoEngageApiV1SegmentationContentActivesegmentsPathResponse>(getGetUmbracoEngageApiV1SegmentationContentActivesegmentsPathUrl(path),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getUmbracoEngageApiV1SegmentationContentActivesegmentsIdResponse200 = {
  data: SegmentedContentResponseModel
  status: 200
}
    
export type getUmbracoEngageApiV1SegmentationContentActivesegmentsIdResponseComposite = getUmbracoEngageApiV1SegmentationContentActivesegmentsIdResponse200;
    
export type getUmbracoEngageApiV1SegmentationContentActivesegmentsIdResponse = getUmbracoEngageApiV1SegmentationContentActivesegmentsIdResponseComposite & {
  headers: Headers;
}

export const getGetUmbracoEngageApiV1SegmentationContentActivesegmentsIdUrl = (id: string,) => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/segmentation/content/activesegments/${id}`
}

export const getUmbracoEngageApiV1SegmentationContentActivesegmentsId = async (id: string, options?: RequestInit): Promise<getUmbracoEngageApiV1SegmentationContentActivesegmentsIdResponse> => {
  
  return customFetch<getUmbracoEngageApiV1SegmentationContentActivesegmentsIdResponse>(getGetUmbracoEngageApiV1SegmentationContentActivesegmentsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


