/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type {
  GetApiV1SearchGetSearchResultsParams,
  SearchResultsModel
} from '.././model';

import { customFetch } from '../../custom-fetch';

export type getApiV1SearchGetSearchResultsResponse200 = {
  data: SearchResultsModel
  status: 200
}

export type getApiV1SearchGetSearchResultsResponse500 = {
  data: void
  status: 500
}
    
export type getApiV1SearchGetSearchResultsResponseComposite = getApiV1SearchGetSearchResultsResponse200 | getApiV1SearchGetSearchResultsResponse500;
    
export type getApiV1SearchGetSearchResultsResponse = getApiV1SearchGetSearchResultsResponseComposite & {
  headers: Headers;
}

export const getGetApiV1SearchGetSearchResultsUrl = (params?: GetApiV1SearchGetSearchResultsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:23142/api/v1/search/getSearchResults?${stringifiedParams}` : `http://localhost:23142/api/v1/search/getSearchResults`
}

export const getApiV1SearchGetSearchResults = async (params?: GetApiV1SearchGetSearchResultsParams, options?: RequestInit): Promise<getApiV1SearchGetSearchResultsResponse> => {
  
  return customFetch<getApiV1SearchGetSearchResultsResponse>(getGetApiV1SearchGetSearchResultsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


