/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Engage API
 * You can find out more about the Umbraco Engage API in [the documentation](https://docs.umbraco.com/umbraco-engage/developers/headless/using-the-marketing-api).
 * OpenAPI spec version: v1
 */

export interface PageEventRequestModel {
  /** @minLength 1 */
  category: string;
  /** @minLength 1 */
  action: string;
  /** @minLength 1 */
  label: string;
  /** @nullable */
  timestamp?: string | null;
}
