/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Engage API
 * You can find out more about the Umbraco Engage API in [the documentation](https://docs.umbraco.com/umbraco-engage/developers/headless/using-the-marketing-api).
 * OpenAPI spec version: v1
 */
import type { SegmentedContentResponseModel } from './segmentedContentResponseModel';

export interface SegmentedContentListResponseModel {
  /** @nullable */
  segmentedContent?: SegmentedContentResponseModel[] | null;
}
