/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Engage API
 * You can find out more about the Umbraco Engage API in [the documentation](https://docs.umbraco.com/umbraco-engage/developers/headless/using-the-marketing-api).
 * OpenAPI spec version: v1
 */
import type {
  SegmentedContentListResponseModel,
  SegmentedContentResponseModel
} from '.././model';

import { customFetch } from '../../custom-fetch';

export type getUmbracoEngageApiV1SegmentationContentSegmentsResponse200 = {
  data: SegmentedContentListResponseModel
  status: 200
}
    
export type getUmbracoEngageApiV1SegmentationContentSegmentsResponseComposite = getUmbracoEngageApiV1SegmentationContentSegmentsResponse200;
    
export type getUmbracoEngageApiV1SegmentationContentSegmentsResponse = getUmbracoEngageApiV1SegmentationContentSegmentsResponseComposite & {
  headers: Headers;
}

export const getGetUmbracoEngageApiV1SegmentationContentSegmentsUrl = () => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/segmentation/content/segments`
}

export const getUmbracoEngageApiV1SegmentationContentSegments = async ( options?: RequestInit): Promise<getUmbracoEngageApiV1SegmentationContentSegmentsResponse> => {
  
  return customFetch<getUmbracoEngageApiV1SegmentationContentSegmentsResponse>(getGetUmbracoEngageApiV1SegmentationContentSegmentsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getUmbracoEngageApiV1SegmentationContentSegmentsPathResponse200 = {
  data: SegmentedContentResponseModel
  status: 200
}
    
export type getUmbracoEngageApiV1SegmentationContentSegmentsPathResponseComposite = getUmbracoEngageApiV1SegmentationContentSegmentsPathResponse200;
    
export type getUmbracoEngageApiV1SegmentationContentSegmentsPathResponse = getUmbracoEngageApiV1SegmentationContentSegmentsPathResponseComposite & {
  headers: Headers;
}

export const getGetUmbracoEngageApiV1SegmentationContentSegmentsPathUrl = (path: string,) => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/segmentation/content/segments/${path}`
}

export const getUmbracoEngageApiV1SegmentationContentSegmentsPath = async (path: string, options?: RequestInit): Promise<getUmbracoEngageApiV1SegmentationContentSegmentsPathResponse> => {
  
  return customFetch<getUmbracoEngageApiV1SegmentationContentSegmentsPathResponse>(getGetUmbracoEngageApiV1SegmentationContentSegmentsPathUrl(path),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getUmbracoEngageApiV1SegmentationContentSegmentsIdResponse200 = {
  data: SegmentedContentResponseModel
  status: 200
}
    
export type getUmbracoEngageApiV1SegmentationContentSegmentsIdResponseComposite = getUmbracoEngageApiV1SegmentationContentSegmentsIdResponse200;
    
export type getUmbracoEngageApiV1SegmentationContentSegmentsIdResponse = getUmbracoEngageApiV1SegmentationContentSegmentsIdResponseComposite & {
  headers: Headers;
}

export const getGetUmbracoEngageApiV1SegmentationContentSegmentsIdUrl = (id: string,) => {


  

  return `http://localhost:23142/umbraco/engage/api/v1/segmentation/content/segments/${id}`
}

export const getUmbracoEngageApiV1SegmentationContentSegmentsId = async (id: string, options?: RequestInit): Promise<getUmbracoEngageApiV1SegmentationContentSegmentsIdResponse> => {
  
  return customFetch<getUmbracoEngageApiV1SegmentationContentSegmentsIdResponse>(getGetUmbracoEngageApiV1SegmentationContentSegmentsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


