/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentRouteModel } from './iApiContentRouteModel';
import type { LinkTypeModel } from './linkTypeModel';

export interface ApiLinkModel {
  /** @nullable */
  readonly url?: string | null;
  /** @nullable */
  readonly queryString?: string | null;
  /** @nullable */
  readonly title?: string | null;
  /** @nullable */
  readonly target?: string | null;
  /** @nullable */
  readonly destinationId?: string | null;
  /** @nullable */
  readonly destinationType?: string | null;
  route?: IApiContentRouteModel;
  linkType?: LinkTypeModel;
}
