/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModel } from './iApiContentModel';

export interface ArticleControlsPropertiesModel {
  /** @nullable */
  articleDate?: string | null;
  /** @nullable */
  author?: IApiContentModel[] | null;
  /** @nullable */
  categories?: IApiContentModel[] | null;
}
