/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { ArticlePropertiesModel } from './articlePropertiesModel';
import type { ArticleContentModelContentType } from './articleContentModelContentType';

export type ArticleContentModel = IApiContentModelBase & {
  properties?: ArticlePropertiesModel;
  contentType: ArticleContentModelContentType;
};
