/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type AuthorListContentModelContentType = typeof AuthorListContentModelContentType[keyof typeof AuthorListContentModelContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthorListContentModelContentType = {
  authorList: 'authorList',
} as const;
