/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { VisibilityControlsPropertiesModel } from './visibilityControlsPropertiesModel';
import type { SEocontrolsPropertiesModel } from './sEocontrolsPropertiesModel';
import type { MainImageControlsPropertiesModel } from './mainImageControlsPropertiesModel';
import type { HeaderControlsPropertiesModel } from './headerControlsPropertiesModel';
import type { ContentControlsPropertiesModel } from './contentControlsPropertiesModel';

export type AuthorListPropertiesModel = VisibilityControlsPropertiesModel & SEocontrolsPropertiesModel & MainImageControlsPropertiesModel & HeaderControlsPropertiesModel & ContentControlsPropertiesModel;
