/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';
import type { AuthorListContentModel } from './authorListContentModel';
import type { AuthorListContentResponseModelContentType } from './authorListContentResponseModelContentType';

export type AuthorListContentResponseModel = IApiContentResponseModelBase & AuthorListContentModel & {
  contentType: AuthorListContentResponseModelContentType;
};
