/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { CodeSnippetRowPropertiesModel } from './codeSnippetRowPropertiesModel';
import type { CodeSnippetRowElementModelContentType } from './codeSnippetRowElementModelContentType';

export type CodeSnippetRowElementModel = IApiElementModelBase & {
  properties?: CodeSnippetRowPropertiesModel;
  contentType: CodeSnippetRowElementModelContentType;
};
