/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';
import type { ErrorContentModel } from './errorContentModel';
import type { ErrorContentResponseModelContentType } from './errorContentResponseModelContentType';

export type ErrorContentResponseModel = IApiContentResponseModelBase & ErrorContentModel & {
  contentType: ErrorContentResponseModelContentType;
};
