/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { HomePropertiesModel } from './homePropertiesModel';
import type { HomeContentModelContentType } from './homeContentModelContentType';

export type HomeContentModel = IApiContentModelBase & {
  properties?: HomePropertiesModel;
  contentType: HomeContentModelContentType;
};
