/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { IApiContentRouteModel } from './iApiContentRouteModel';

export type IApiContentModelBase = IApiElementModelBase & {
  readonly id?: string;
  readonly contentType: string;
  /** @nullable */
  readonly name?: string | null;
  readonly createDate?: string;
  readonly updateDate?: string;
  route?: IApiContentRouteModel;
};
