/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiMediaWithCropsModel } from './iApiMediaWithCropsModel';
import type { ApiLinkModel } from './apiLinkModel';

export interface IconLinkRowPropertiesModel {
  /** @nullable */
  icon?: IApiMediaWithCropsModel[] | null;
  /** @nullable */
  link?: ApiLinkModel[] | null;
}
