/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiMediaWithCropsModel } from './iApiMediaWithCropsModel';

export interface ImageRowPropertiesModel {
  /** @nullable */
  image?: IApiMediaWithCropsModel[] | null;
  /** @nullable */
  caption?: string | null;
}
