/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { LoginPropertiesModel } from './loginPropertiesModel';
import type { LoginContentModelContentType } from './loginContentModelContentType';

export type LoginContentModel = IApiContentModelBase & {
  properties?: LoginPropertiesModel;
  contentType: LoginContentModelContentType;
};
