/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { RichTextModelBlocksItem } from './richTextModelBlocksItem';

export interface RichTextModel {
  markup: string;
  blocks: RichTextModelBlocksItem[];
}
