/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { VideoRowSettingsPropertiesModel } from './videoRowSettingsPropertiesModel';
import type { VideoRowSettingsElementModelContentType } from './videoRowSettingsElementModelContentType';

export type VideoRowSettingsElementModel = IApiElementModelBase & {
  properties?: VideoRowSettingsPropertiesModel;
  contentType: VideoRowSettingsElementModelContentType;
};
